# Generated by Django 4.0.4 on 2022-05-31 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='mobile',
            new_name='mobilenum',
        ),
    ]
