# Generated by Django 4.0.4 on 2022-05-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0002_rename_mobile_employee_mobilenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobilenum',
            field=models.CharField(default='', max_length=15),
        ),
    ]
